INSERT INTO product (name_p, size, material, manufacture, cost)
VALUES  ((SELECT name_p FROM name_p WHERE name_p.name_p = "комплект"), 	  (SELECT size FROM size WHERE size.size = "Двуспальный стандарт"), (SELECT material FROM material WHERE material.material = "бязь"),  (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Китай"),   700.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "комплект"), 	  (SELECT size FROM size WHERE size.size = "Двуспальный стандарт"), (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Турция"),  600.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "комплект"), 	  (SELECT size FROM size WHERE size.size = "Полуторный стандарт"),  (SELECT material FROM material WHERE material.material = "ситец"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Россия"),  500.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "комплект"), 	  (SELECT size FROM size WHERE size.size = "Европейский"),  	    (SELECT material FROM material WHERE material.material = "бязь"),  (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Китай"),   800.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "комплект"), 	  (SELECT size FROM size WHERE size.size = "Односпальный стандарт"),(SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Китай"),   400.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "пододеяльник"),(SELECT size FROM size WHERE size.size = "150*220"),  	    (SELECT material FROM material WHERE material.material = "шелк"),  (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Турция"),  300.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "пододеяльник"),(SELECT size FROM size WHERE size.size = "210*220"),		    (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Украина"), 200.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "простыня"),	  (SELECT size FROM size WHERE size.size = "100*220"),  	    (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Украина"), 100.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "простыня"),	  (SELECT size FROM size WHERE size.size = "210*220"),  	    (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Украина"), 120.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "наволочка"),	  (SELECT size FROM size WHERE size.size = "50*70"),  		    (SELECT material FROM material WHERE material.material = "шелк"),  (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Турция"),  100.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "наволочка"),	  (SELECT size FROM size WHERE size.size = "60*60"),  		    (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Украина"), 50.00),
	((SELECT name_p FROM name_p WHERE name_p.name_p = "наволочка"),   (SELECT size FROM size WHERE size.size = "70*70"),  		    (SELECT material FROM material WHERE material.material = "сатин"), (SELECT manufacture FROM manufacture  WHERE manufacture.manufacture  = "Китай"),   60.00);	
