INSERT INTO input(id_p, input.number, input.Data)
VALUES	((SELECT id_p FROM product WHERE product.id_p = 2  AND product.name_p = "комплект" 	AND product.size = "Двуспальный стандарт" AND product.material = "сатин" AND product.manufacture  = "Турция"  AND cost = 600), 5,  NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 7  AND product.name_p = "пододеяльник"  AND product.size = "210*220" 		  AND product.material = "сатин" AND product.manufacture  = "Украина" AND cost = 200), 10, NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 6  AND product.name_p = "пододеяльник"  AND product.size = "150*220" 		  AND product.material = "шелк"  AND product.manufacture  = "Турция"  AND cost = 300), 2,  NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 8  AND product.name_p = "простыня" 	AND product.size = "100*220" 		  AND product.material = "сатин" AND product.manufacture  = "Украина" AND cost = 100), 10, NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 11 AND product.name_p = "наволочка" 	AND product.size = "60*60" 		  AND product.material = "сатин" AND product.manufacture  = "Украина" AND cost = 50),  10, NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 12 AND product.name_p = "наволочка" 	AND product.size = "70*70" 		  AND product.material = "сатин" AND product.manufacture  = "Китай"   AND cost = 60),  10, NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 1  AND product.name_p = "комплект" 	AND product.size = "Двуспальный стандарт" AND product.material = "бязь"  AND product.manufacture  = "Китай"   AND cost = 700), 2,  NOW()+ INTERVAL 1 MONTH + INTERVAL 3 DAY),
	((SELECT id_p FROM product WHERE product.id_p = 1  AND product.name_p = "комплект" 	AND product.size = "Двуспальный стандарт" AND product.material = "бязь"  AND product.manufacture  = "Китай"   AND cost = 700), 3,  NOW()),
	((SELECT id_p FROM product WHERE product.id_p = 4  AND product.name_p = "комплект" 	AND product.size = "Европейский" 	  AND product.material = "бязь"  AND product.manufacture  = "Китай"   AND cost = 800), 5,  NOW()+ INTERVAL 1 MONTH + INTERVAL 3 DAY),
	((SELECT id_p FROM product WHERE product.id_p = 5  AND product.name_p = "комплект" 	AND product.size = "Односпальный стандарт"AND product.material = "сатин" AND product.manufacture  = "Китай"   AND cost = 400), 4,  NOW()+ INTERVAL 1 MONTH + INTERVAL 5 DAY),
	((SELECT id_p FROM product WHERE product.id_p = 3  AND product.name_p = "комплект" 	AND product.size = "Полуторный стандарт"  AND product.material = "ситец" AND product.manufacture  = "Россия"  AND cost = 500), 1,  NOW()+ INTERVAL 1 MONTH + INTERVAL 5 DAY);	
